name: release

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.10"
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v5
      with:
        python-version: "${{ env.PYTHON_VERSION }}"
    - name: 'Install build dependencies'
      run: |
        python3 --version
        python3 -m pip install build
    - name: 'Paranoid cleanup'
      run: |
        rm -rf dist/
    - name: 'Build a wheel and source distribution packages'
      run: |
        python3 -m build
        ls -al dist/
    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: intel-variant-provider-py${{ env.PYTHON_VERSION }}
        path: dist/
    - name: 'Create GitHub Release'
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: dist/*
        prerelease: ${{ contains(github.ref, '-rc') }}
