name: test

on: [push, pull_request]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: 'Install variantlib'
      run: |
        # aligning version if variantlib with the one used in this project:
        # * https://github.com/wheelnext/pep_xxx_wheel_variants
        python3 -m pip install git+https://github.com/wheelnext/variantlib@0dd7795
    - name: 'Install project'
      run: |
        python3 --version
        python3 -m pip install -e .
        python3 -m pip install -e ".[test]"
    - name: 'Run pytest'
      run: |
        python3 -m pytest tests/
    - name: 'Test variantlib plugins list'
      run: |
        variantlib plugins list >_list.txt
        grep intel _list.txt
    - name: 'Test for supported configs on the system'
      run: |
        variantlib plugins get-configs -s >_configs_supported.txt
        # File should be empty as runner does not have intel gpu
        test ! -s _configs_supported.txt
    - name: 'Test for all configs'
      run: |
        variantlib plugins get-configs -a >_configs_all.txt
        test -s _configs_all.txt
        grep "intel :: device_ip ::" _configs_all.txt
        ! grep -v "intel :: device_ip ::" _configs_all.txt
